"""Initial Migration

Revision ID: 2031e08c350b
Revises: abf0c3b894e4
Create Date: 2021-09-14 22:31:48.632342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031e08c350b'
down_revision = 'abf0c3b894e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
